[package]
name = "four_on_the_floor"
version = "0.1.0"
edition = "2021"

[dependencies]
rodio = "0.17"
ctrlc = "3.2"
midly = "0.5.3"
midir = "0.10.1"
threadpool = "1.8"
eframe = "0.23"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
